Update Trezor to 9.0.11
Getting error:

TypeError: Cannot destructure property 'BridgeV2' of 'transport_1.default' as it is undefined.

This seems to have changed recently (within the last couple of days) as this is breaking in one of our automated tests.

Info:

@trezor/connect v9.0.7

How to reproduce
This happens consistently when trying to import the module.


Update to 9.0.11 should solve this